src/java/Authenticate/AuthenticateController.java
package Authenticate;

import Controller.UserController;
import Controller.util.Message;
import Model.User;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 *
 * @author Rodrigo
 */
@Named(value = "authenticateController")
@ViewScoped
public class AuthenticateController implements Serializable {

    private UserController userController;

    public UserController getUserController() {
        return userController;
    }

    public void setUserController(UserController userController) {
        this.userController = userController;
    }

    public User getUserContext() {
        return (User) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("user");
    }

    public void setUserContext(User user) {
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("user", user);
    }

    public void invalidateSession() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
    }

    public String accessValidation() {
        User user = this.findUser();
        if (user != null && this.userPasswordValidate(user)) {
            setUserContext(user);
            return "faces/index.xhtml?faces-redirect=true";
        }
        Message.addErrorMessage("Usuário ou Senha incorretos!");
        return null;
    }
    
    private User findUser() {
        Map<String, Object> filters = new HashMap<>();
        filters.put("login", userController.getSelected().getLogin());
        return userController.getItems(0, 0, null, null, filters).stream().findAny().orElse(null);
    }

    private Boolean userPasswordValidate(User userRegister) {
        return this.userController.getSelected().getPassword().equals(userRegister.getPassword());
    }
    
}

web/template/appmenu.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>
        <h:form id="menuForm">
            <p:menubar>

                <p:menuitem value="#{myBundle.Home}" 
                            outcome="/index" 
                            icon="ui-icon-home"/>

                <p:submenu label="#{myBundle.Maintenance}">

                    <p:menuitem value="#{myBundle.HierarchyHeading}" 
                                outcome="/index/hierarchy/index" />

                    <p:menuitem value="#{myBundle.StatusHeading}" 
                                outcome="/index/status/index" />

                    <p:menuitem value="#{myBundle.TicketHeading}" 
                                outcome="/index/ticket/index" />

                    <p:menuitem value="#{myBundle.UserHeading}" 
                                outcome="/index/user/index" />

                </p:submenu>

                <f:facet name="options">

                    <p:outputLabel value="#{authenticateController.userContext.name}" />

                    <p:spacer height="20" />

                    <p:commandButton id="logoutButton"
                                     icon="ui-icon-extlink" 
                                     value="#{myBundle.Logout}" 
                                     actionListener="#{authenticateController.invalidateSession()}"
                                     action="/authenticate.xhtml?faces-redirect=true"/>

                </f:facet>

            </p:menubar>
        </h:form>
    </ui:composition>

</html>

web/template/confirmation.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:confirmDialog global="true"> 
        
        <p:commandButton value="#{myBundle.Yes}" 
                         type="button" 
                         styleClass="ui-confirmdialog-yes" 
                         icon="ui-icon-check"/>  
        
        <p:commandButton value="#{myBundle.No}" 
                         type="button" 
                         styleClass="ui-confirmdialog-no" 
                         icon="ui-icon-close"/>  
        
    </p:confirmDialog>

</ui:composition>

web/template/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="pfcrud.css"/>
        <h:outputScript library="scripts" name="pfcrud.js"/>
    </h:head>

    <h:body>

        <p:growl id="growl" sticky="true"/>

        <p:layout fullPage="true">
            
            <p:layoutUnit position="north" 
                          size="100" 
                          header="#{myBundle.AppName}">

                <ui:include src="/template/appmenu.xhtml"/>
                
            </p:layoutUnit>

            <p:layoutUnit position="south" 
                          size="60">
                
                <ui:insert name="footer"/>
                
            </p:layoutUnit>

            <p:layoutUnit position="center">
                <ui:insert name="body"/>
            </p:layoutUnit>

        </p:layout>

    </h:body>

</html>